/**
 * Async inbox backfill for campaign sends — decoupled from send hot path.
 */
const Interaction = require('../models/Interaction');
const { generateChatRef } = require('../utils/chatRefHelper');
const { buildWhatsAppTemplatePreview } = require('../utils/whatsappTemplatePreview');
const logger = require('../config/logger');

/**
 * Upsert inbox threads for a batch of successfully sent campaign messages.
 *
 * @param {object} params
 * @param {string} params.organizationId
 * @param {string} params.phoneNumberId
 * @param {string} params.connectionId
 * @param {string} params.campaignId
 * @param {string} params.campaignName
 * @param {string} params.templateName
 * @param {string} params.languageCode
 * @param {string} params.templateLabel
 * @param {object|null} params.dbTemplate
 * @param {Array<object>} params.items — { recipientPhone, recipientName, messageId, components }
 */
async function upsertCampaignThreadsBatch({
  organizationId,
  phoneNumberId,
  connectionId,
  campaignId,
  campaignName,
  templateName,
  languageCode,
  templateLabel,
  dbTemplate,
  items
}) {
  if (!items?.length || !phoneNumberId) return { upserted: 0 };

  let upserted = 0;
  const now = new Date();

  for (const item of items) {
    if (!item.messageId) continue;

    try {
      const threadPlatformId = `dm_${String(phoneNumberId)}_${String(item.recipientPhone)}`;

      const existing = await Interaction.findOne({
        platformId: threadPlatformId,
        organization: organizationId
      })
        .select('_id chatRef')
        .lean();

      let chatRefData = null;
      if (!existing?.chatRef) {
        chatRefData = await generateChatRef(organizationId).catch(() => null);
      }

      const preview = buildWhatsAppTemplatePreview(
        {
          name: templateName,
          languageCode,
          components: item.components || []
        },
        dbTemplate || null
      );
      preview.campaignId = String(campaignId);
      preview.campaignName = campaignName;

      const replyDoc = {
        content: preview.bodyText || templateLabel,
        sentAt: now,
        platformResponseId: item.messageId,
        wasAutoGenerated: false,
        status: 'sent',
        messageType: 'whatsapp_template',
        whatsappTemplatePreview: preview,
        deliveryStatus: 'sent',
        deliveryStatusAt: now
      };

      const setFields = {
        organization: organizationId,
        platform: 'whatsapp',
        platformConnection: connectionId,
        type: 'dm',
        threadId: String(item.recipientPhone),
        'metadata.phoneNumberId': String(phoneNumberId),
        content: preview.bodyText || templateLabel,
        author: {
          platformId: String(item.recipientPhone),
          name: item.recipientName || item.recipientPhone,
          username: item.recipientPhone
        },
        platformCreatedAt: now
      };

      const setOnInsertFields = {
        source: 'campaign',
        status: 'unread',
        isRead: false
      };

      if (!existing && chatRefData?.chatRef) {
        setOnInsertFields.chatNumber = chatRefData.chatNumber;
        setOnInsertFields.chatRef = chatRefData.chatRef;
      } else if (existing && !existing.chatRef && chatRefData?.chatRef) {
        setFields.chatNumber = chatRefData.chatNumber;
        setFields.chatRef = chatRefData.chatRef;
      }

      await Interaction.findOneAndUpdate(
        {
          platformId: threadPlatformId,
          organization: organizationId,
          'replies.platformResponseId': { $ne: item.messageId }
        },
        {
          $set: setFields,
          $setOnInsert: setOnInsertFields,
          $push: { replies: replyDoc }
        },
        { upsert: true }
      );
      upserted++;
    } catch (err) {
      logger.warn('[CampaignInbox] Thread upsert failed', {
        campaignId,
        phone: item.recipientPhone,
        error: err.message
      });
    }
  }

  return { upserted };
}

module.exports = {
  upsertCampaignThreadsBatch
};
