/**
 * Unit tests for agentActivity — the helper that holds ReppyAI auto-reply back
 * while a human agent is actively handling a conversation.
 *
 * The signals must survive a new inbound (isRead resets, readAt/readBy + last
 * manual reply do not), and the AI's own replies must never count as agent
 * activity (or the AI would hold itself back forever).
 */

const {
  resolveHoldMinutes,
  getLastManualReplyAt,
  getLastAgentActivity,
  getLastAgentActivityAt,
  isAgentRecentlyActive,
  DEFAULT_HOLD_MINUTES,
} = require('../../../src/utils/agentActivity');

const minutesAgo = (m) => new Date(Date.now() - m * 60 * 1000);
const userId = '507f1f77bcf86cd799439011';

describe('resolveHoldMinutes', () => {
  it('defaults to 5 when unset', () => {
    expect(resolveHoldMinutes(undefined)).toBe(DEFAULT_HOLD_MINUTES);
    expect(resolveHoldMinutes({})).toBe(5);
  });
  it('honours a configured value', () => {
    expect(resolveHoldMinutes({ agentActiveHoldMinutes: 10 })).toBe(10);
  });
  it('allows 0 (disabled)', () => {
    expect(resolveHoldMinutes({ agentActiveHoldMinutes: 0 })).toBe(0);
  });
  it('clamps out-of-range values to [0, 60]', () => {
    expect(resolveHoldMinutes({ agentActiveHoldMinutes: -5 })).toBe(0);
    expect(resolveHoldMinutes({ agentActiveHoldMinutes: 999 })).toBe(60);
  });
  it('falls back to default for non-numeric input', () => {
    expect(resolveHoldMinutes({ agentActiveHoldMinutes: 'abc' })).toBe(5);
    expect(resolveHoldMinutes({ agentActiveHoldMinutes: NaN })).toBe(5);
  });
});

describe('getLastManualReplyAt', () => {
  it('returns null when there are no replies', () => {
    expect(getLastManualReplyAt({ replies: [] })).toBeNull();
    expect(getLastManualReplyAt({})).toBeNull();
  });
  it('ignores auto-generated replies', () => {
    const interaction = {
      replies: [
        { wasAutoGenerated: true, sentAt: minutesAgo(1) },
        { wasAutoGenerated: true, sentAt: minutesAgo(0.5) },
      ],
    };
    expect(getLastManualReplyAt(interaction)).toBeNull();
  });
  it('returns the most-recent manual reply timestamp', () => {
    const manualAt = minutesAgo(2);
    const interaction = {
      replies: [
        { wasAutoGenerated: false, sentAt: minutesAgo(30) },
        { wasAutoGenerated: false, sentAt: manualAt },
        { wasAutoGenerated: true, sentAt: minutesAgo(1) }, // later, but auto → ignored
      ],
    };
    expect(getLastManualReplyAt(interaction).getTime()).toBe(manualAt.getTime());
  });
});

describe('getLastAgentActivity', () => {
  it('uses readAt only when readBy is set', () => {
    expect(getLastAgentActivity({ readAt: minutesAgo(1) }).source).toBeNull(); // no readBy
    const r = getLastAgentActivity({ readAt: minutesAgo(1), readBy: userId });
    expect(r.source).toBe('read');
  });
  it('picks the more recent of read vs manual reply', () => {
    const readNewer = getLastAgentActivity({
      readAt: minutesAgo(1),
      readBy: userId,
      replies: [{ wasAutoGenerated: false, sentAt: minutesAgo(5) }],
    });
    expect(readNewer.source).toBe('read');

    const replyNewer = getLastAgentActivity({
      readAt: minutesAgo(5),
      readBy: userId,
      replies: [{ wasAutoGenerated: false, sentAt: minutesAgo(1) }],
    });
    expect(replyNewer.source).toBe('reply');
  });
  it('returns null source when no signals present', () => {
    expect(getLastAgentActivity({}).at).toBeNull();
    expect(getLastAgentActivityAt({})).toBeNull();
  });
});

describe('isAgentRecentlyActive', () => {
  it('active when an agent opened the chat 2 min ago (hold 5)', () => {
    const r = isAgentRecentlyActive({ readAt: minutesAgo(2), readBy: userId }, 5);
    expect(r.active).toBe(true);
    expect(r.source).toBe('read');
  });
  it('inactive when the agent opened the chat 10 min ago (hold 5)', () => {
    const r = isAgentRecentlyActive({ readAt: minutesAgo(10), readBy: userId }, 5);
    expect(r.active).toBe(false);
  });
  it('active when the agent manually replied 1 min ago', () => {
    const r = isAgentRecentlyActive(
      { replies: [{ wasAutoGenerated: false, sentAt: minutesAgo(1) }] },
      5
    );
    expect(r.active).toBe(true);
    expect(r.source).toBe('reply');
  });
  it('inactive when only the AI has replied', () => {
    const r = isAgentRecentlyActive(
      { replies: [{ wasAutoGenerated: true, sentAt: minutesAgo(0.2) }] },
      5
    );
    expect(r.active).toBe(false);
  });
  it('inactive when there is no agent signal at all', () => {
    expect(isAgentRecentlyActive({}, 5).active).toBe(false);
  });
  it('holdMinutes = 0 disables the hold even with very recent activity', () => {
    const r = isAgentRecentlyActive({ readAt: minutesAgo(0.1), readBy: userId }, 0);
    expect(r.active).toBe(false);
  });
});
