/**
 * Automation Hub Controller
 * Provides aggregated KPIs, module status, top performers and recent activity
 * for the Automation Hub dashboard page.
 */
const Organization = require('../models/Organization');
const Interaction = require('../models/Interaction');
const PlatformConnection = require('../models/PlatformConnection');
const ReviewRequestSettings = require('../models/ReviewRequestSettings');
const RetargetingFlow = require('../models/RetargetingFlow');
const WhatsAppFlow = require('../models/WhatsAppFlow');
const logger = require('../config/logger');

const DAY_MS = 24 * 60 * 60 * 1000;

/**
 * GET /api/v1/automation/hub-overview
 * Returns KPIs + module enabled state + recent activity + top performers.
 * All aggregations target the last 7 days.
 */
exports.getHubOverview = async (req, res, next) => {
  try {
    const orgId = req.user.organization._id;
    const since = new Date(Date.now() - 7 * DAY_MS);
    const prevSince = new Date(Date.now() - 14 * DAY_MS);

    const [org, connections, reviewSettings, activeRetargeting, activeWaFlow] = await Promise.all([
      Organization.findById(orgId)
        .select('autoReplySettings escalationSettings commentToDmSettings commentFollowInviteSettings salesFlowSettings storyToDmSettings')
        .lean(),
      PlatformConnection.find({ organization: orgId, status: 'connected', isActive: true })
        .select('platform platformData.displayName platformData.displayPhoneNumber')
        .lean(),
      ReviewRequestSettings.findOne({ organization: orgId }).select('enabled').lean(),
      RetargetingFlow.countDocuments({ organization: orgId, status: 'active' }),
      WhatsAppFlow.countDocuments({ organization: orgId, status: 'active' })
    ]);

    // ── KPI aggregations ────────────────────────────────────────────────────
    const [
      autoRepliedNow, autoRepliedPrev,
      escalatedNow, escalatedPrev,
      revenueNow, revenuePrev,
      leadsNow, leadsPrev,
      aiAccuracyNow
    ] = await Promise.all([
      Interaction.countDocuments({ organization: orgId, wasAutoGenerated: true, createdAt: { $gte: since } }),
      Interaction.countDocuments({ organization: orgId, wasAutoGenerated: true, createdAt: { $gte: prevSince, $lt: since } }),
      Interaction.countDocuments({ organization: orgId, requiresHumanResponse: true, createdAt: { $gte: since } }),
      Interaction.countDocuments({ organization: orgId, requiresHumanResponse: true, createdAt: { $gte: prevSince, $lt: since } }),
      _revenueSum(orgId, since),
      _revenueSum(orgId, prevSince, since),
      Interaction.countDocuments({ organization: orgId, status: 'new', createdAt: { $gte: since } }),
      Interaction.countDocuments({ organization: orgId, status: 'new', createdAt: { $gte: prevSince, $lt: since } }),
      _aiAccuracy(orgId, since)
    ]);

    // ── Recent activity (last 10 auto-replied or escalated interactions) ────
    const recentActivity = await Interaction.find({
      organization: orgId,
      $or: [{ wasAutoGenerated: true }, { requiresHumanResponse: true }],
      createdAt: { $gte: since }
    })
      .sort({ updatedAt: -1 })
      .limit(10)
      .select('platform type status requiresHumanResponse wasAutoGenerated updatedAt author')
        .lean();

    // ── Module enabled states ────────────────────────────────────────────────
    const modules = [
      {
        id: 'ai-replies',
        label: 'AI Auto Replies',
        description: 'Reply instantly to DMs, comments, stories and mentions using AI.',
        icon: 'fas fa-comment-dots',
        route: '/app/automation/ai-replies',
        active: org?.autoReplySettings?.enabled ?? false
      },
      {
        id: 'growth',
        label: 'Growth Automation',
        description: 'Convert comments to DM, gain followers and drive more sales.',
        icon: 'fas fa-seedling',
        route: '/app/automation/growth',
        active: (org?.commentToDmSettings?.enabled || org?.commentFollowInviteSettings?.enabled || org?.salesFlowSettings?.enabled || org?.storyToDmSettings?.enabled) ?? false
      },
      {
        id: 'whatsapp-flows',
        label: 'WhatsApp Journeys',
        description: 'Automate bookings, support, purchases and more on WhatsApp.',
        icon: 'fab fa-whatsapp',
        route: '/app/automation/whatsapp-flows',
        active: activeWaFlow > 0
      },
      {
        id: 'reviews',
        label: 'Review Collection',
        description: 'Automatically collect more positive reviews and build trust.',
        icon: 'fas fa-star',
        route: '/app/automation/reviews',
        active: reviewSettings?.enabled === true
      },
      {
        id: 'retargeting',
        label: 'Retargeting',
        description: 'Re-engage interested users and convert them to loyal customers.',
        icon: 'fas fa-bullseye',
        route: '/app/automation/retargeting',
        active: activeRetargeting > 0
      },
      {
        id: 'escalation',
        label: 'Human Escalation',
        description: 'Smartly transfer complex conversations to your team or agents.',
        icon: 'fas fa-headset',
        route: '/app/automation/escalation',
        active: org?.escalationSettings?.enabled ?? true
      }
    ];

    // ── Top performers by platform ────────────────────────────────────────────
    const topByPlatform = await Interaction.aggregate([
      { $match: { organization: orgId, wasAutoGenerated: true, createdAt: { $gte: since } } },
      { $group: { _id: '$platform', count: { $sum: 1 } } },
      { $sort: { count: -1 } },
      { $limit: 4 }
    ]);

    // ── Connected channels ────────────────────────────────────────────────────
    const channels = connections.map(c => ({
      platform: c.platform,
      name: c.platformData?.displayName || c.platformData?.displayPhoneNumber || c.platform
    }));

    return res.json({
      success: true,
      data: {
        kpis: {
          conversationsAutomated: { value: autoRepliedNow, change: _pct(autoRepliedNow, autoRepliedPrev) },
          humanEscalations: { value: escalatedNow, change: _pct(escalatedNow, escalatedPrev) },
          revenueGenerated: { value: revenueNow, change: _pct(revenueNow, revenuePrev) },
          leadsCaptured: { value: leadsNow, change: _pct(leadsNow, leadsPrev) },
          aiAccuracy: { value: aiAccuracyNow, change: 0 }
        },
        modules,
        recentActivity: recentActivity.map(i => ({
          platform: i.platform,
          type: i.type,
          isEscalated: !!i.requiresHumanResponse,
          wasAutoGenerated: i.wasAutoGenerated,
          updatedAt: i.updatedAt,
          authorName: i.author?.name || i.author?.platformId || 'User'
        })),
        topByPlatform,
        channels
      }
    });
  } catch (err) {
    logger.error('[automationHubController] getHubOverview error', { error: err.message });
    next(err);
  }
};

// ── helpers ──────────────────────────────────────────────────────────────────

async function _revenueSum(orgId, from, to) {
  try {
    const ProductOrder = require('../models/ProductOrder');
    const match = { organization: orgId, status: 'completed', createdAt: { $gte: from } };
    if (to) match.createdAt.$lt = to;
    const r = await ProductOrder.aggregate([
      { $match: match },
      { $group: { _id: null, total: { $sum: '$amount' } } }
    ]);
    return r[0]?.total ?? 0;
  } catch {
    return 0;
  }
}

async function _aiAccuracy(orgId, since) {
  try {
    const total = await Interaction.countDocuments({ organization: orgId, wasAutoGenerated: true, createdAt: { $gte: since } });
    if (!total) return 0;
    const failed = await Interaction.countDocuments({
      organization: orgId, wasAutoGenerated: true, requiresHumanResponse: true, createdAt: { $gte: since }
    });
    return Math.round(((total - failed) / total) * 100);
  } catch {
    return 0;
  }
}

function _pct(now, prev) {
  if (!prev) return now > 0 ? 100 : 0;
  return Math.round(((now - prev) / prev) * 100);
}
