/**
 * Agent-activity helpers — used to hold ReppyAI auto-reply back while a human
 * agent is actively handling a conversation.
 *
 * Why this exists: `isRead` is reset to false on every new inbound message, so the
 * old "agent read this exact message during the delay window" guard misses an agent
 * who is mid-conversation (chat already open, or typing a reply). These helpers use
 * signals that SURVIVE a new inbound — `readAt`/`readBy` (agent opened the chat) and
 * the last manual (non-auto) reply's `sentAt` (agent replied) — to decide whether a
 * human touched the thread recently.
 *
 * Pure functions, no DB access — safe to require from both the API (scheduler) and
 * the worker (auto-reply job).
 */

const DEFAULT_HOLD_MINUTES = 5;
const MIN_HOLD_MINUTES = 0;   // 0 disables the feature (old behavior)
const MAX_HOLD_MINUTES = 60;

/** Coerce a value into a Date, or null if it isn't a usable timestamp. */
function toDate(value) {
  if (!value) return null;
  const d = value instanceof Date ? value : new Date(value);
  return Number.isNaN(d.getTime()) ? null : d;
}

/**
 * Resolve the configured hold window (minutes) from an org's autoReplySettings,
 * clamped to [MIN, MAX]. Falls back to the 5-minute default when unset.
 * @param {object} [autoReplySettings]
 * @returns {number}
 */
function resolveHoldMinutes(autoReplySettings) {
  const raw = autoReplySettings?.agentActiveHoldMinutes;
  const n = typeof raw === 'number' && !Number.isNaN(raw) ? raw : DEFAULT_HOLD_MINUTES;
  return Math.min(MAX_HOLD_MINUTES, Math.max(MIN_HOLD_MINUTES, n));
}

/**
 * Timestamp of the last manual (human) reply in a thread — the last replies[] entry
 * with wasAutoGenerated !== true. AI/auto replies (wasAutoGenerated === true) never
 * count, so the AI can never hold itself back.
 * @param {object} interaction
 * @returns {Date|null}
 */
function getLastManualReplyAt(interaction) {
  const replies = interaction?.replies;
  if (!Array.isArray(replies) || replies.length === 0) return null;
  for (let i = replies.length - 1; i >= 0; i--) {
    const r = replies[i];
    if (r && r.wasAutoGenerated !== true) {
      // A human reply — use sentAt (fall back to createdAt if present).
      return toDate(r.sentAt) || toDate(r.createdAt) || null;
    }
  }
  return null;
}

/**
 * Most-recent moment a human agent touched this conversation: the later of
 *   - readAt (only when readBy is set → an agent actually opened it), and
 *   - the last manual reply's sentAt.
 * @param {object} interaction
 * @returns {{ at: Date|null, source: 'read'|'reply'|null }}
 */
function getLastAgentActivity(interaction) {
  const readAt = interaction?.readBy ? toDate(interaction.readAt) : null;
  const replyAt = getLastManualReplyAt(interaction);

  if (readAt && replyAt) {
    return readAt >= replyAt
      ? { at: readAt, source: 'read' }
      : { at: replyAt, source: 'reply' };
  }
  if (readAt) return { at: readAt, source: 'read' };
  if (replyAt) return { at: replyAt, source: 'reply' };
  return { at: null, source: null };
}

/** Convenience: just the Date (or null) of the last agent activity. */
function getLastAgentActivityAt(interaction) {
  return getLastAgentActivity(interaction).at;
}

/**
 * True when a human agent opened or manually replied to this conversation within
 * the last `holdMinutes` minutes — i.e. the AI should stand down.
 * @param {object} interaction
 * @param {number} holdMinutes  0 disables the check
 * @returns {{ active: boolean, at: Date|null, source: 'read'|'reply'|null, ageMs: number|null }}
 */
function isAgentRecentlyActive(interaction, holdMinutes) {
  const { at, source } = getLastAgentActivity(interaction);
  if (!holdMinutes || holdMinutes <= 0 || !at) {
    return { active: false, at, source, ageMs: at ? Date.now() - at.getTime() : null };
  }
  const ageMs = Date.now() - at.getTime();
  return { active: ageMs < holdMinutes * 60 * 1000, at, source, ageMs };
}

module.exports = {
  DEFAULT_HOLD_MINUTES,
  MIN_HOLD_MINUTES,
  MAX_HOLD_MINUTES,
  resolveHoldMinutes,
  getLastManualReplyAt,
  getLastAgentActivity,
  getLastAgentActivityAt,
  isAgentRecentlyActive,
};
